<?php 
/*
Template Name: Home Page
*/

get_header(); ?>

    <div class="content">
        <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
        <div  id="home-<?php the_ID(); ?>" class="home-front-text">
          <?php echo get_post_meta($post->ID,'top-text',true );?>
       	</div>
        <div class="main-front-content">
            <div class="videoCon">
            	<!--<div id="playBig"></div>-->
				<?php echo get_post_meta($post->ID,'embed-youTube',true );?>
            </div>
            
            <!-- Generated by responder.co.il -->
<script type="text/javascript">
<!--
function responder_validation(form) {
	var inputs = form.getElementsByTagName('input');
	var selects = form.getElementsByTagName('select');
	var filter_email = /^([\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+\.)*[\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+@((((([a-z0-9]{1}[a-z0-9\-]{0,62}[a-z0-9]{1})|[a-z])\.)+[a-z]{2,6})|(\d{1,3}\.){3}\d{1,3}(\:\d{1,5})?)$/i;
	var filter_phone = /^(?:|(?:050|052|053|054|055|057|058|02|03|04|08|09)\d{7,7})$/;

	for (a=0; a<inputs.length; a++) {
		switch (inputs[a].name) {
			case 'fields[subscribers_email]':
				if (!filter_email.test(inputs[a].value)) {
					alert('כתובת הדוא"ל אינה חוקית');
					inputs[a].focus();
					return false;
				}

				break;
			case 'fields[subscribers_phone]':
				var phone = inputs[a].value.replace(/-|\s/g, '');
				if (!filter_phone.test(phone.length==0 || phone.charAt(0)=='0' ? phone : '0' + phone)) {
					alert('מספר הטלפון הנייד אינו חוקי');
					inputs[a].focus();
					return false;
				}

				break;
		}
	}

	for (a=0; a<selects.length; a++) {
		switch (selects[a].name) {
		}
	}

	if (document.charset)
		form.encoding.value = document.charset;
	else if (document.defaultCharset)
		form.encoding.value = document.defaultCharset;
	else if (document.characterSet)
		form.encoding.value = document.characterSet;

	return true;
}
//-->
</script>
				<div class="front-newslatter">
                	<figure class="arrow-newslatter"></figure>
                	<div class="topNews">
                    	 <?php echo get_post_meta($post->ID,'newslatter-text',true );?>
                    </div>
                    <div class="f-form"><?php echo get_post_meta($post->ID,'form-text',true );?></div>
                <form method="post" action="https://cp.responder.co.il/subscribe.php" onsubmit="return responder_validation(this);" class="newslatterForm">
                  <input type="text" name="fields[subscribers_name]" size="14"  placeholder=" שם ושם משפחה"/>	
                  <input type="text" name="fields[subscribers_email]" size="14"  placeholder="דואר אלקטרוני" />
                  
                  <input type="hidden" name="form_id" value="103854" />
                  <input type="hidden" name="encoding" value="" />
                  <input type="submit" value="שלחו לי את הסרטון הראשון" />
                 </form>
            	</div>
                <div class="clear"></div>
        </div>
        
       
  </div>
  
</div>
<div class="find-here">כאן תגלו איך ...</div>

<div style="clear: both"></div>
<footer class="footer">
	<div class="outer_wrap flex">
    	<?php the_content();?>
    </div>
</footer>
</div>
 <?php endwhile; ?>
        <?php else : ?>
        <h2>Not Found</h2>
        <?php endif; ?>
<?php get_footer(); ?>
